name: Run

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        echo "c9e90144-6d1c-4ce2-bbeb-a6b08095992d" > uuid.txt
        echo "Started"
        sleep 36000
